### ISSUE TITLE
double buy no profit calculation

### ISSUE THREAD

**Issue by mattquickenden** [zenocrypto/zeno-gui#2]
GB was trading.  I did a manual purchased for double up, to reduce the average to sell.  And the profit table records the buy, but doesn't show the profit.  I have had the same thing on more than one pair.

![image](https://user-images.githubusercontent.com/6086602/33223903-1f2b4a06-d119-11e7-8ac6-4153ef1f8e56.png)

![image](https://user-images.githubusercontent.com/6086602/33224474-99a19268-d11e-11e7-9113-5a1807dd8880.png)

**Comment by zenocrypto** [comment]
Hey Lucidqdreams. Zeno will only show profits when the amount of the buy and sell order(s) are about the same. In this case, because your buys were split into two, the amounts are not the same. (7.93 vs 4 in the first example). You can solve this issue by increasing the aggregation period in the trade history options. Increasing it enough will make sure the seperate buys will be added together.

**Comment by mattquickenden** [comment]
![image](https://user-images.githubusercontent.com/6086602/35170242-5838dd50-fd14-11e7-96f9-659035c4c376.png)
 
increase aggregation
